SELECT P.AGN_IN_CODIGO AS CODIGO_MEGA, 
P.AGN_ST_NOME AS NOME, 
P.AGN_ST_FANTASIA AS FANTASIA, 
P.AGN_ST_CGC AS CNPJ
FROM MGGLO.GLO_AGENTES P
WHERE P.AGN_IN_CODIGO NOT IN (SELECT O.AGN_IN_CODIGO FROM MGGLO.GLO_ENDAGENTES O WHERE O.TEA_ST_CODIGO = 'COB')--SEM END COBRANÇA
AND P.AGN_IN_CODIGO IN (SELECT C.AGN_IN_CODIGO FROM MGGLO.GLO_AGENTES_ID C WHERE C.AGN_CH_STATUS = 'A' AND C.AGN_TAU_ST_CODIGO = 'C' AND C.AGN_DT_INICIOMOV <= SYSDATE) --ATIVOS
and p.Agn_In_Codigo NOT IN (SELECT Q.AGN_IN_CODIGO FROM MGGLO.GLO_AGENTECAMPOESPECIFICO Q WHERE Q.AGN_BO_PROSPECTADO = 'S')-- PROSPECÇÃO


