



WITH

REVISAO_MAIS_REC AS
(
--traz a formulação mais recente
SELECT  ITENSLISTAMATERIAIS.PRO_TAB_IN_CODIGO,
    ITENSLISTAMATERIAIS.PRO_PAD_IN_CODIGO,
    ITENSLISTAMATERIAIS.PRO_IN_CODIGO,
    ITENSLISTAMATERIAIS.COM_TAB_IN_CODIGO,
    ITENSLISTAMATERIAIS.COM_PAD_IN_CODIGO,
    ITENSLISTAMATERIAIS.COM_IN_CODIGO
FROM  MGADM.EST_ITENSLISTAMATERIAIS   ITENSLISTAMATERIAIS
INNER JOIN
  (
  SELECT   ITENSLISTAMATERIAIS_AUX.PRO_IN_CODIGO,
      ITENSLISTAMATERIAIS_AUX.PRO_PAD_IN_CODIGO,
      ITENSLISTAMATERIAIS_AUX.PRO_TAB_IN_CODIGO,
      MAX(ITENSLISTAMATERIAIS_AUX.LIS_IN_REVISAO) AS REVMAX
  FROM  MGADM.EST_ITENSLISTAMATERIAIS   ITENSLISTAMATERIAIS_AUX
  GROUP BY ITENSLISTAMATERIAIS_AUX.PRO_IN_CODIGO,
       ITENSLISTAMATERIAIS_AUX.PRO_PAD_IN_CODIGO,
       ITENSLISTAMATERIAIS_AUX.PRO_TAB_IN_CODIGO
  ) TABAUX ON
ITENSLISTAMATERIAIS.PRO_IN_CODIGO     = TABAUX.PRO_IN_CODIGO     AND
ITENSLISTAMATERIAIS.PRO_PAD_IN_CODIGO = TABAUX.PRO_PAD_IN_CODIGO AND
ITENSLISTAMATERIAIS.PRO_TAB_IN_CODIGO = TABAUX.PRO_TAB_IN_CODIGO AND
ITENSLISTAMATERIAIS.LIS_IN_REVISAO    = TABAUX.REVMAX
GROUP BY ITENSLISTAMATERIAIS.PRO_IN_CODIGO,
     ITENSLISTAMATERIAIS.PRO_TAB_IN_CODIGO,
     ITENSLISTAMATERIAIS.PRO_PAD_IN_CODIGO,
     ITENSLISTAMATERIAIS.LIS_IN_REVISAO,
     ITENSLISTAMATERIAIS.COM_IN_CODIGO,
     ITENSLISTAMATERIAIS.COM_TAB_IN_CODIGO,
     ITENSLISTAMATERIAIS.COM_PAD_IN_CODIGO
),

ACHAR_FILHOS AS
(
--acha os semi-acabados dos níveis abaixo do produto em análise
SELECT  REVISAO_MAIS_REC.*,
    LEVEL AS NIVEL,
    PRODUTOS_FILHO.PRO_ST_DEFITEM AS PRO_ST_DEFITEM_FILHO
FROM  REVISAO_MAIS_REC

LEFT JOIN MGADM.EST_PRODUTOS PRODUTOS_FILHO ON
REVISAO_MAIS_REC.COM_TAB_IN_CODIGO = PRODUTOS_FILHO.PRO_TAB_IN_CODIGO AND
REVISAO_MAIS_REC.COM_PAD_IN_CODIGO = PRODUTOS_FILHO.PRO_PAD_IN_CODIGO AND
REVISAO_MAIS_REC.COM_IN_CODIGO     = PRODUTOS_FILHO.PRO_IN_CODIGO

START WITH REVISAO_MAIS_REC.PRO_IN_CODIGO = &CodMega
CONNECT BY REVISAO_MAIS_REC.PRO_IN_CODIGO = PRIOR REVISAO_MAIS_REC.COM_IN_CODIGO
),

SELECIONAR_ORDENS AS
(
SELECT  PRO_ORDENS.PRO_IN_CODIGO        AS PRO_IN_CODIGO_ORD,
    PRO_ORDENS.PRO_PAD_IN_CODIGO      AS PRO_PAD_IN_CODIGO_ORD,
    PRO_ORDENS.PRO_TAB_IN_CODIGO      AS PRO_TAB_IN_CODIGO_ORD,
    PRO_ORDENS.ORD_IN_CODIGO,
    PRO_ORDENS.ORD_SEQ_IN_CODIGO,
    PRO_ORDENS.ORD_TAB_IN_CODIGO,
    MIN(CSC_MOVIMENTO.CPE_IN_CODIGO)    AS CPE_IN_CODIGO,
    MIN(CSC_MOVIMENTO.CPE_PAD_IN_CODIGO)  AS CPE_PAD_IN_CODIGO,
    MIN(CSC_MOVIMENTO.CPE_TAB_IN_CODIGO)  AS CPE_TAB_IN_CODIGO

FROM MGCSC.CSC_MOVIMENTO CSC_MOVIMENTO

INNER JOIN MGCSC.CSC_MOVIMENTOVINC CSC_MOVIMENTOVINC ON
CSC_MOVIMENTO.CSC_IN_CODIGO     = CSC_MOVIMENTOVINC.CSC_IN_CODIGO     AND
CSC_MOVIMENTO.FIL_IN_CODIGO     = CSC_MOVIMENTOVINC.FIL_IN_CODIGO     AND
CSC_MOVIMENTO.ORG_IN_CODIGO     = CSC_MOVIMENTOVINC.ORG_IN_CODIGO     AND
CSC_MOVIMENTO.ORG_PAD_IN_CODIGO = CSC_MOVIMENTOVINC.ORG_PAD_IN_CODIGO AND
CSC_MOVIMENTO.ORG_TAB_IN_CODIGO = CSC_MOVIMENTOVINC.ORG_TAB_IN_CODIGO AND
CSC_MOVIMENTO.ORG_TAU_ST_CODIGO = CSC_MOVIMENTOVINC.ORG_TAU_ST_CODIGO AND
CSC_MOVIMENTO.SEQ_IN_CODIGOCSC  = CSC_MOVIMENTOVINC.SEQ_IN_CODIGOCSC  AND
CSC_MOVIMENTO.TAB_IN_CODIGOCSC  = CSC_MOVIMENTOVINC.TAB_IN_CODIGOCSC

INNER JOIN MGMAN.PRO_ORDENS PRO_ORDENS ON
CSC_MOVIMENTOVINC.FIL_IN_CODIGO     = PRO_ORDENS.FIL_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORD_IN_CODIGO     = PRO_ORDENS.ORD_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORD_SEQ_IN_CODIGO = PRO_ORDENS.ORD_SEQ_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORD_TAB_IN_CODIGO = PRO_ORDENS.ORD_TAB_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_IN_CODIGO     = PRO_ORDENS.ORG_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORG_PAD_IN_CODIGO = PRO_ORDENS.ORG_PAD_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_TAB_IN_CODIGO = PRO_ORDENS.ORG_TAB_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_TAU_ST_CODIGO = PRO_ORDENS.ORG_TAU_ST_CODIGO

WHERE  PRO_ORDENS.PRO_IN_CODIGO IN (
    SELECT  ACHAR_FILHOS.COM_IN_CODIGO FROM ACHAR_FILHOS
    WHERE  ACHAR_FILHOS.PRO_ST_DEFITEM_FILHO = 'CO'
    UNION
    SELECT  &CodMega FROM DUAL)
    
GROUP BY PRO_ORDENS.PRO_IN_CODIGO,
     PRO_ORDENS.PRO_PAD_IN_CODIGO,
     PRO_ORDENS.PRO_TAB_IN_CODIGO,
     PRO_ORDENS.ORD_IN_CODIGO,
     PRO_ORDENS.ORD_SEQ_IN_CODIGO,
     PRO_ORDENS.ORD_TAB_IN_CODIGO
    
HAVING  MIN(CSC_MOVIMENTO.CPE_IN_CODIGO) BETWEEN 
(SELECT MAX(CUS.CPE_IN_CODIGO)-3 AS PRI_PER FROM MGCSC.CSC_MOVIMENTO CUS) AND 
(SELECT MAX(CUS.CPE_IN_CODIGO)-1 AS PRI_PER FROM MGCSC.CSC_MOVIMENTO CUS)
),

ORDEM_DETAL AS
(
SELECT  PRO_ORDENS.PRO_IN_CODIGO    AS PRO_IN_CODIGO_ORD,
    PRO_ORDENS.PRO_PAD_IN_CODIGO  AS PRO_PAD_IN_CODIGO_ORD,
    PRO_ORDENS.PRO_TAB_IN_CODIGO  AS PRO_TAB_IN_CODIGO_ORD,
    PRO_ORDENS.ORD_IN_CODIGO,
    PRO_ORDENS.ORD_SEQ_IN_CODIGO,
    PRO_ORDENS.ORD_TAB_IN_CODIGO,
    CSC_MOVIMENTO.TMC_ST_CODIGO,
    SELECIONAR_ORDENS.CPE_IN_CODIGO,
    SELECIONAR_ORDENS.CPE_PAD_IN_CODIGO,
    SELECIONAR_ORDENS.CPE_TAB_IN_CODIGO,
    CSC_MOVIMENTOVINC.MAQ_IN_CODIGO,
    CSC_MOVIMENTOVINC.MAQ_PAD_IN_CODIGO,
    CSC_MOVIMENTOVINC.MAQ_TAB_IN_CODIGO,
    CSC_MOVIMENTOVINC.CEL_IN_CODIGO,
    CSC_MOVIMENTOVINC.CEL_PAD_IN_CODIGO,
    CSC_MOVIMENTOVINC.CEL_TAB_IN_CODIGO,
    CSC_MOVIMENTO.PRO_IN_CODIGO,
    CSC_MOVIMENTO.PRO_PAD_IN_CODIGO,
    CSC_MOVIMENTO.PRO_TAB_IN_CODIGO,
    SUM(
      CSC_MOVIMENTOVALORIZADO.CMV_RE_MAO_OBRA        +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_DESP4        +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_DESP5        +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_DESP6        +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_DESPESAFIXA      +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_DESPESAVARIAVEL    +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_BENEFICIAMENTO    +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_MATERIALIMPORTADO  +
      CSC_MOVIMENTOVALORIZADO.CMV_RE_MATERIALNACIONAL
       ) AS CUSTOS_DESPESAS,
    SUM(CSC_MOVIMENTOVALORIZADO.CMV_RE_QUANTIDADE) AS RE_QUANTIDADE,
    CASE WHEN SUM(CSC_MOVIMENTOVALORIZADO.CMV_RE_HORA) <> 0 THEN  
      SUM(CSC_MOVIMENTOVALORIZADO.CMV_RE_HORA)
    END AS CMV_RE_HORA
FROM MGCSC.CSC_MOVIMENTO CSC_MOVIMENTO

INNER JOIN MGCSC.CSC_MOVIMENTOVINC CSC_MOVIMENTOVINC ON
CSC_MOVIMENTO.CSC_IN_CODIGO     = CSC_MOVIMENTOVINC.CSC_IN_CODIGO     AND
CSC_MOVIMENTO.FIL_IN_CODIGO     = CSC_MOVIMENTOVINC.FIL_IN_CODIGO     AND
CSC_MOVIMENTO.ORG_IN_CODIGO     = CSC_MOVIMENTOVINC.ORG_IN_CODIGO     AND
CSC_MOVIMENTO.ORG_PAD_IN_CODIGO = CSC_MOVIMENTOVINC.ORG_PAD_IN_CODIGO AND
CSC_MOVIMENTO.ORG_TAB_IN_CODIGO = CSC_MOVIMENTOVINC.ORG_TAB_IN_CODIGO AND
CSC_MOVIMENTO.ORG_TAU_ST_CODIGO = CSC_MOVIMENTOVINC.ORG_TAU_ST_CODIGO AND
CSC_MOVIMENTO.SEQ_IN_CODIGOCSC  = CSC_MOVIMENTOVINC.SEQ_IN_CODIGOCSC  AND
CSC_MOVIMENTO.TAB_IN_CODIGOCSC  = CSC_MOVIMENTOVINC.TAB_IN_CODIGOCSC

INNER JOIN MGCSC.CSC_MOVIMENTOVALORIZADO CSC_MOVIMENTOVALORIZADO ON
CSC_MOVIMENTOVINC.CSC_IN_CODIGO     = CSC_MOVIMENTOVALORIZADO.CSC_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORG_IN_CODIGO     = CSC_MOVIMENTOVALORIZADO.ORG_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORG_PAD_IN_CODIGO = CSC_MOVIMENTOVALORIZADO.ORG_PAD_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_TAB_IN_CODIGO = CSC_MOVIMENTOVALORIZADO.ORG_TAB_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_TAU_ST_CODIGO = CSC_MOVIMENTOVALORIZADO.ORG_TAU_ST_CODIGO AND
CSC_MOVIMENTOVINC.SEQ_IN_CODIGOCSCV = CSC_MOVIMENTOVALORIZADO.SEQ_IN_CODIGOCSCV AND
CSC_MOVIMENTOVINC.TAB_IN_CODIGOCSC  = CSC_MOVIMENTOVALORIZADO.TAB_IN_CODIGOCSC  AND
CSC_MOVIMENTOVINC.FIL_IN_CODIGO     = CSC_MOVIMENTOVALORIZADO.FIL_IN_CODIGO

INNER JOIN MGMAN.PRO_ORDENS PRO_ORDENS ON
CSC_MOVIMENTOVINC.FIL_IN_CODIGO     = PRO_ORDENS.FIL_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORD_IN_CODIGO     = PRO_ORDENS.ORD_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORD_SEQ_IN_CODIGO = PRO_ORDENS.ORD_SEQ_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORD_TAB_IN_CODIGO = PRO_ORDENS.ORD_TAB_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_IN_CODIGO     = PRO_ORDENS.ORG_IN_CODIGO     AND
CSC_MOVIMENTOVINC.ORG_PAD_IN_CODIGO = PRO_ORDENS.ORG_PAD_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_TAB_IN_CODIGO = PRO_ORDENS.ORG_TAB_IN_CODIGO AND
CSC_MOVIMENTOVINC.ORG_TAU_ST_CODIGO = PRO_ORDENS.ORG_TAU_ST_CODIGO

INNER JOIN SELECIONAR_ORDENS ON
PRO_ORDENS.PRO_IN_CODIGO     = SELECIONAR_ORDENS.PRO_IN_CODIGO_ORD     AND
PRO_ORDENS.PRO_PAD_IN_CODIGO = SELECIONAR_ORDENS.PRO_PAD_IN_CODIGO_ORD AND
PRO_ORDENS.PRO_TAB_IN_CODIGO = SELECIONAR_ORDENS.PRO_TAB_IN_CODIGO_ORD AND
PRO_ORDENS.ORD_IN_CODIGO     = SELECIONAR_ORDENS.ORD_IN_CODIGO         AND
PRO_ORDENS.ORD_SEQ_IN_CODIGO = SELECIONAR_ORDENS.ORD_SEQ_IN_CODIGO     AND
PRO_ORDENS.ORD_TAB_IN_CODIGO = SELECIONAR_ORDENS.ORD_TAB_IN_CODIGO

WHERE  CSC_MOVIMENTO.TMC_ST_CODIGO IN ('900','901','905','906','920','922')

GROUP BY SELECIONAR_ORDENS.CPE_IN_CODIGO,
     SELECIONAR_ORDENS.CPE_PAD_IN_CODIGO,
     SELECIONAR_ORDENS.CPE_TAB_IN_CODIGO,
     CSC_MOVIMENTO.TMC_ST_CODIGO,
     PRO_ORDENS.PRO_IN_CODIGO,
     PRO_ORDENS.PRO_PAD_IN_CODIGO,
     PRO_ORDENS.PRO_TAB_IN_CODIGO,
     PRO_ORDENS.ORD_IN_CODIGO,
     PRO_ORDENS.ORD_SEQ_IN_CODIGO,
     PRO_ORDENS.ORD_TAB_IN_CODIGO,
     CSC_MOVIMENTO.PRO_IN_CODIGO,
     CSC_MOVIMENTO.PRO_PAD_IN_CODIGO,
     CSC_MOVIMENTO.PRO_TAB_IN_CODIGO,
     CSC_MOVIMENTOVINC.MAQ_IN_CODIGO,
     CSC_MOVIMENTOVINC.MAQ_PAD_IN_CODIGO,
     CSC_MOVIMENTOVINC.MAQ_TAB_IN_CODIGO,
     CSC_MOVIMENTOVINC.CEL_IN_CODIGO,
     CSC_MOVIMENTOVINC.CEL_PAD_IN_CODIGO,
     CSC_MOVIMENTOVINC.CEL_TAB_IN_CODIGO
),

INF_PRO_PRI AS
(
--informações do produto principal
SELECT  PRO_ST_ALTERNATIVO,
    PRO_ST_DESCRICAO,
    PRO_ST_DEFITEM,
    PRO_ST_CODREAL
FROM  MGADM.EST_PRODUTOS EST_PRODUTOS
WHERE  PRO_IN_CODIGO = &CodMega
)

SELECT  (SELECT INF_PRO_PRI.PRO_ST_CODREAL FROM INF_PRO_PRI) AS PRO_ST_CODREAL_PRI,  
    (SELECT INF_PRO_PRI.PRO_ST_ALTERNATIVO FROM INF_PRO_PRI) AS PRO_ST_ALTERNATIVO_PRI,
    (SELECT INF_PRO_PRI.PRO_ST_DESCRICAO   FROM INF_PRO_PRI) AS PRO_ST_DESCRICAO_PRI,
    (SELECT INF_PRO_PRI.PRO_ST_DEFITEM     FROM INF_PRO_PRI) AS PRO_ST_DEFITEMO_PRI,
    ORDEM_DETAL.PRO_IN_CODIGO_ORD,
    ORDEM_DETAL.PRO_PAD_IN_CODIGO_ORD,
    ORDEM_DETAL.PRO_TAB_IN_CODIGO_ORD,
    ORDEM_DETAL.CPE_IN_CODIGO,
    ORDEM_DETAL.CPE_PAD_IN_CODIGO,
    ORDEM_DETAL.CPE_TAB_IN_CODIGO,
    CASE ORDEM_DETAL.TMC_ST_CODIGO 
      WHEN '901' THEN ORDEM_DETAL.PRO_IN_CODIGO
      WHEN '906' THEN ORDEM_DETAL.PRO_IN_CODIGO
      WHEN '920' THEN 9998
      WHEN '922' THEN 9999
    END AS COD_MEGA,
    CASE ORDEM_DETAL.TMC_ST_CODIGO 
      WHEN '901' THEN EST_PRODUTOS.PRO_ST_ALTERNATIVO
      WHEN '906' THEN EST_PRODUTOS.PRO_ST_ALTERNATIVO
    END AS COD_ALT,
    CASE ORDEM_DETAL.TMC_ST_CODIGO 
      WHEN '901' THEN EST_PRODUTOS.PRO_ST_DESCRICAO
      WHEN '906' THEN EST_PRODUTOS.PRO_ST_DESCRICAO
      WHEN '920' THEN 'BENEFICIAMENTO'
      WHEN '922' THEN PRO_CELULA.CEL_ST_NOME||' - '||PRO_MAQUINA.MAQ_ST_NOME
    END AS DESCRICAO,
    CASE ORDEM_DETAL.TMC_ST_CODIGO 
      WHEN '901' THEN ORDEM_DETAL.RE_QUANTIDADE
      WHEN '906' THEN ORDEM_DETAL.RE_QUANTIDADE
      --FALTA COLOCAR A QTD DO BENEFICIAMENTO
    END AS RE_QUANTIDADE,
    CASE ORDEM_DETAL.TMC_ST_CODIGO 
      WHEN '901' THEN EST_PRODUTOS.UNI_ST_UNIDADE
      WHEN '906' THEN EST_PRODUTOS.UNI_ST_UNIDADE
      --FALTA COLOCAR A QTD DO BENEFICIAMENTO
    END AS UNI_ST_UNIDADE,
    EST_PRODUTOS_ORD.PRO_ST_DESCRICAO  AS PRO_ST_DESCRICAO_ORD,
    EST_PRODUTOS_ORD.UNI_ST_UNIDADE    AS UNI_ST_UNIDADE_ORD,
    CASE ORDEM_DETAL.TMC_ST_CODIGO 
      WHEN '901' THEN EST_PRODUTOS.PRO_ST_DEFITEM
      WHEN '906' THEN EST_PRODUTOS.PRO_ST_DEFITEM
    END AS PRO_ST_DEFITEM,
    EST_PRODUTOS_ORD.PRO_ST_DEFITEM    AS PRO_ST_DEFITEM_ORD,
    ORDEM_DETAL.ORD_IN_CODIGO,
    ORDEM_DETAL.ORD_SEQ_IN_CODIGO,
    ORDEM_DETAL.ORD_TAB_IN_CODIGO,
    ORDEM_DETAL.CUSTOS_DESPESAS,
    ORDEM_DETAL.CMV_RE_HORA,
    (
    SELECT  SUM(ORDEM_DETAL_AUX.RE_QUANTIDADE) FROM ORDEM_DETAL ORDEM_DETAL_AUX
    WHERE  ORDEM_DETAL_AUX.ORD_IN_CODIGO     = ORDEM_DETAL.ORD_IN_CODIGO     AND
        ORDEM_DETAL_AUX.ORD_SEQ_IN_CODIGO = ORDEM_DETAL.ORD_SEQ_IN_CODIGO AND
        ORDEM_DETAL_AUX.ORD_TAB_IN_CODIGO = ORDEM_DETAL.ORD_TAB_IN_CODIGO AND
        ORDEM_DETAL_AUX.TMC_ST_CODIGO IN ('900','905')
    ) AS QTD_ORDEM,
    (
    SELECT  SUM(ORDEM_DETAL_AUX.RE_QUANTIDADE) FROM ORDEM_DETAL ORDEM_DETAL_AUX
    WHERE  ORDEM_DETAL_AUX.PRO_IN_CODIGO_ORD     = ORDEM_DETAL.PRO_IN_CODIGO_ORD     AND
        ORDEM_DETAL_AUX.PRO_PAD_IN_CODIGO_ORD = ORDEM_DETAL.PRO_PAD_IN_CODIGO_ORD AND
        ORDEM_DETAL_AUX.PRO_TAB_IN_CODIGO_ORD = ORDEM_DETAL.PRO_TAB_IN_CODIGO_ORD AND
        ORDEM_DETAL_AUX.TMC_ST_CODIGO IN ('900','905')
    ) AS QTD_TOT_PROD,
    --traz o nível do produto. O produto principal será o nível 0, o S.A. será o nível 1
    --caso tenha outro S.A. abaixo, será o nível 2 e assim por diante
    CASE WHEN ORDEM_DETAL.PRO_IN_CODIGO_ORD = &CodMega THEN 0
    ELSE
      (
      SELECT  MAX(ACHAR_FILHOS.NIVEL) FROM ACHAR_FILHOS
      WHERE  ACHAR_FILHOS.PRO_IN_CODIGO     = ORDEM_DETAL.PRO_IN_CODIGO_ORD     AND
          ACHAR_FILHOS.PRO_PAD_IN_CODIGO = ORDEM_DETAL.PRO_PAD_IN_CODIGO_ORD AND
          ACHAR_FILHOS.PRO_TAB_IN_CODIGO = ORDEM_DETAL.PRO_TAB_IN_CODIGO_ORD
      )
    END AS  NIVEL,
    ORDEM_DETAL.TMC_ST_CODIGO
FROM  ORDEM_DETAL





LEFT JOIN MGADM.EST_PRODUTOS EST_PRODUTOS ON
ORDEM_DETAL.PRO_TAB_IN_CODIGO = EST_PRODUTOS.PRO_TAB_IN_CODIGO AND
ORDEM_DETAL.PRO_PAD_IN_CODIGO = EST_PRODUTOS.PRO_PAD_IN_CODIGO AND
ORDEM_DETAL.PRO_IN_CODIGO     = EST_PRODUTOS.PRO_IN_CODIGO

LEFT JOIN MGADM.EST_PRODUTOS EST_PRODUTOS_ORD ON
ORDEM_DETAL.PRO_TAB_IN_CODIGO_ORD = EST_PRODUTOS_ORD.PRO_TAB_IN_CODIGO AND
ORDEM_DETAL.PRO_PAD_IN_CODIGO_ORD = EST_PRODUTOS_ORD.PRO_PAD_IN_CODIGO AND
ORDEM_DETAL.PRO_IN_CODIGO_ORD     = EST_PRODUTOS_ORD.PRO_IN_CODIGO

LEFT JOIN MGMAN.PRO_CELULA PRO_CELULA ON
ORDEM_DETAL.CEL_IN_CODIGO     = PRO_CELULA.CEL_IN_CODIGO     AND
ORDEM_DETAL.CEL_PAD_IN_CODIGO = PRO_CELULA.CEL_PAD_IN_CODIGO AND
ORDEM_DETAL.CEL_TAB_IN_CODIGO = PRO_CELULA.CEL_TAB_IN_CODIGO

LEFT JOIN MGMAN.PRO_MAQUINA PRO_MAQUINA ON
ORDEM_DETAL.MAQ_IN_CODIGO     = PRO_MAQUINA.MAQ_IN_CODIGO     AND
ORDEM_DETAL.MAQ_PAD_IN_CODIGO = PRO_MAQUINA.MAQ_PAD_IN_CODIGO AND
ORDEM_DETAL.MAQ_TAB_IN_CODIGO = PRO_MAQUINA.MAQ_TAB_IN_CODIGO

WHERE  ORDEM_DETAL.TMC_ST_CODIGO NOT IN ('900','905')
