select O.AGN_IN_CODIGO AS CODIGO_AGENTE, O.Agn_St_Nome AS NOME, O.AGN_ST_FANTASIA AS FANTASIA, 
P.AGN_TAU_ST_CODIGO AS TIPO, P.PLA_IN_REDUZIDO AS REDUZIDO, T.PLA_ST_DESCRICAO AS DESCRICAO

from MGGLO.GLO_CONTASAGENTES P, MGGLO.GLO_AGENTES O, MGCON.CON_PLANO_CONTA T
WHERE P.AGN_IN_CODIGO = O.AGN_IN_CODIGO
AND P.PLA_IN_REDUZIDO = T.PLA_IN_REDUZIDO
