SELECT DISTINCT(COD_PROD) FROM


(SELECT 
NF.NOT_IN_NUMERO AS NOTA,NF.NOT_DT_EMISSAO AS DATANF,
ITN.PRO_IN_CODIGO AS COD_PROD, PROD.PRO_ST_DESCRICAO AS PRODUTO,
ITNFE.ITN_ST_CEAN AS GTIN

FROM MGVEN.VEN_NOTAFISCAL NF, MGVEN.VEN_ITEMNOTAFISCAL ITN, 
MGNFE.NFE_NOTAFISCAL NFNFE, MGNFE.NFE_ITEMNOTAFISCAL ITNFE, MGADM.EST_PRODUTOS PROD

WHERE NF.NOT_IN_CODIGO = ITN.NOT_IN_CODIGO
AND NF.NOT_IN_NUMERO = NFNFE.NOT_IN_NNF
AND NFNFE.NOT_IN_SEQUENCIA = ITNFE.NOT_IN_SEQUENCIA
AND ITN.PRO_IN_CODIGO = PROD.PRO_IN_CODIGO
AND NF.NOT_DT_EMISSAO > '01-JAN-2019'
AND ITNFE.ITN_ST_CEAN LIKE ('%7896020470076%'))
--AND ITN.PRO_IN_CODIGO = 3995 




