INSERT INTO MGGLO.GLO_PESSOA_AGENTES (AGN_TAB_IN_CODIGO,
AGN_PAD_IN_CODIGO,
AGN_IN_CODIGO,
PAG_IN_CODIGO,
PAG_ST_NOME,
CAR_IN_CODIGO,
PAG_DT_NASCIMENTO,
PAG_ST_TELRESIDENCIAL,
PAG_ST_CELULAR,
PAG_ST_TELCOMERCIAL,
PAG_ST_RAMAL,
PAG_ST_EMAIL,
PAG_ST_DEPART,
PAG_ST_IDENTIDADE,
PAG_ST_CPF,
PAG_ST_OBSERVACAO,
PAG_CH_TIPO,
TPR_IN_CODIGO,
PAG_CH_SEXO,
PAG_CH_ESTADOCIVIL,
PAG_BO_RESPFISCAL,
PAG_BO_RESPFINANC,
PAG_BO_SINCRONIZAPORTAL)

select

53 AS AGN_TAB_IN_CODIGO,
1 AS AGN_PAD_IN_CODIGO,
CLI.AGN_IN_CODIGO AS AGN_IN_CODIGO,
999 AS PAG_IN_CODIGO,-- codigo do contato no agente, se este insert nunca foi usado para os clientes deste rep usar 999  se for cadastrar um segundo email, usar 998...997..996 etc...
'DANFE' AS PAG_ST_NOME,
NULL AS CAR_IN_CODIGO,
NULL AS PAG_DT_NASCIMENTO,
NULL AS PAG_ST_TELRESIDENCIAL,
NULL AS PAG_ST_CELULAR,
NULL AS PAG_ST_TELCOMERCIAL,
NULL AS PAG_ST_RAMAL,
'&EMAIL' AS PAG_ST_EMAIL,
NULL AS PAG_ST_DEPART,
NULL AS PAG_ST_IDENTIDADE,
NULL AS PAG_ST_CPF,
NULL AS PAG_ST_OBSERVACAO,
'C' AS PAG_CH_TIPO,
1 AS TPR_IN_CODIGO,
'N' AS PAG_CH_SEXO,
'N' AS PAG_CH_ESTADOCIVIL,
'N' AS PAG_BO_RESPFISCAL,
'N' AS PAG_BO_RESPFINANC,
'N' AS PAG_BO_SINCRONIZAPORTAL


from mgglo.Glo_Agentes CLI, mgglo.Glo_Agentes REP, MGGLO.GLO_RELACAO_CLI_REP CLIREP
WHERE CLI.AGN_IN_CODIGO = CLIREP.CLI_AGN_IN_CODIGO
AND REP.AGN_IN_CODIGO = CLIREP.REP_AGN_IN_CODIGO
AND REP.AGN_IN_CODIGO = &REP

