select PREC.AGN_IN_CODIGO AS COD_AGENTE,
FORN.AGN_ST_FANTASIA AS FANTASIA_AGENTE,
PREC.Pro_In_Codigo AS COD_PRODUTO,
PROD.PRO_ST_DESCRICAO AS NOME_PRODUTO,
PF.MTF_ST_NOME AS NOME_PRODUTO_FORN,
PF.MTF_ST_SEUCODIGO AS COD_PRODUTO_FORNEC,
PREC.PRE_RE_PRECO AS VALOR,             -- O QUE EU QUERO
IND.IND_ST_NOME AS MOEDA,
PREC.TPR_ST_TIPOPRECO AS TIPO_PRECO

from MGADM.EST_PRECOSAGE PREC, MGADM.EST_PRODUTOS PROD, MGGLO.GLO_AGENTES FORN, 
MGGLO.GLO_INDICE_FINANCEIRO IND, MGADM.EST_MATLFORNEC PF  --DE ONDE 

WHERE PREC.PRO_IN_CODIGO = PROD.PRO_IN_CODIGO 
AND PREC.AGN_IN_CODIGO = FORN.AGN_IN_CODIGO
AND PREC.IND_IN_CODIGO = IND.IND_IN_CODIGO
AND PF.AGN_IN_CODIGO = FORN.AGN_IN_CODIGO
AND PF.PRO_IN_CODIGO = PROD.PRO_IN_CODIGO

--COMO EU QUERO


