SELECT DISTINCT SEL.* FROM
(SELECT 

AGN_CERT.AGN_IN_CODIGO AS CODIGO_AGENTE,
AGN_CERT.CERT_IN_SEQUENCIAL AS SEQUENCIAL_CERTIFICADO,
AGN_CERT.AGNC_DT_VALIDADE  AS VAL_CERTIFICADO,
AGN.AGN_ST_FANTASIA AS NOME_AGENTE,
CERT.CERT_ST_NOME AS NOME_CERTIFICADO,
EMP_CERT.CTF_ST_NOME AS NOME_CERTIFICADORA,

nvl((Select 'X' from MGGLO.GLO_AGENTES_ID I
       where i.Agn_In_Codigo     = AGN.AGN_IN_CODIGO
         AND I.AGN_TAU_ST_CODIGO = 'C'),' ') as CLIENTE,

nvl((Select 'X' from MGGLO.GLO_AGENTES_ID I
       where i.Agn_In_Codigo     = AGN.AGN_IN_CODIGO
         AND I.AGN_TAU_ST_CODIGO = 'F'),' ') as FORNECEDOR
         

FROM  

MGGLO.GLO_AGENTECERT AGN_CERT,     -- CERTIFICAÇÃO DO AGENTE
MGGLO.GLO_AGENTES AGN,
MGGLO.GLO_AGENTES_ID AGN_ID, --TIPO AGENTE
MGGLO.GLO_CERTIFICADO CERT, -- certificado
MGGLO.GLO_CERTIFICADOR EMP_CERT  -- CERTIFICADORA

WHERE 

AGN.AGN_IN_CODIGO           = AGN_CERT.AGN_IN_CODIGO   AND
AGN_CERT.CERT_IN_SEQUENCIAL = CERT.CERT_IN_SEQUENCIAL   AND
AGN_CERT.CTF_IN_CODIGO      = EMP_CERT.CTF_IN_CODIGO  AND
AGN_ID.AGN_IN_CODIGO        = AGN.AGN_IN_CODIGO 

AND AGN_ID.AGN_CH_STATUS = 'A'     --       TODOS OS AGENTES ATIVOS 
AND  (AGN_CERT.AGNC_DT_VALIDADE - SYSDATE) <= 60  -- SO MOSTRA REGISTROS QUE A DATA TENHA 2 MESES DE DIFERENÇA
)  SEL -- ALIAS DO SELECT





















/*SELECT cer.* ,cer.rowid
  FROM MGGLO.GLO_CERTIFICADO cer -- certificado

 
 
 SELECT EMP.*,EMP.ROWID
  FROM MGGLO.GLO_CERTIFICADOR EMP -- certificadora
  

  
  
  SELECT * FROM  MGGLO.GLO_AGENTECERT     -- CERTIFICAÇÃO DO AGENTE
  
  
  */
  
