SELECT INS.* FROM 

--MGADM.EST_MOVIMENTO MOV, 
--MGADM.EST_LOTESMOVIMENTO LOTE_MOV, 
MGADM.EST_LOTESINSPECAO LOTE_INS, 
MGADM.EST_ITENSINSPECAO INS,
MGADM.EST_PRODUTOS PROD

WHERE 

--MOV.MVT_IN_LANCAM = LOTE_MOV.MVT_IN_LANCAM             AND 
--LOTE_MOV.MVL_ST_LOTEFORNE = LOTE_INS.LIN_ST_LOTEFORNE  AND 
LOTE_INS.INS_IN_SEQUENCIA = INS.INS_IN_SEQUENCIA       AND
INS.PRO_IN_CODIGO = PROD.PRO_IN_CODIGO                 AND
PROD.PRO_ST_DEFITEM = 'MP'

