SELECT PRO.PRO_IN_CODIGO AS COD_PRODUTO,
PRO.PRO_ST_DESCRICAO AS DESCRICAO_PRODUTO,
CLA.APL_IN_CODIGO AS COD_APLICACAO,    --OQUE?
CLA.CLA_IN_REDUZIDO AS CLASSE_FIN

FROM MGVEN.VEN_NOTAFISCAL NF, MGVEN.VEN_ITEMNOTAFISCAL ITNF,MGADM.EST_PRODUTOS PRO,MGADM.EST_PRODUTOCLASSE CLA

WHERE NF.NOT_IN_CODIGO = ITNF.NOT_IN_CODIGO
AND ITNF.PRO_IN_CODIGO = PRO.PRO_IN_CODIGO
AND PRO.PRO_IN_CODIGO = CLA.PRO_IN_CODIGO
AND CLA.APL_IN_CODIGO = ITNF.APL_IN_CODIGO


AND nf.not_in_numero = 7944    --NOTA ESPECIFICA DE CONSULTA LAIRTON
AND nf.not_dt_emissao > '01-jan-2021' -- FILTRANDO NOTAS DESTE ANO, POIS TEM NUMERAÇÃO DUPLICADA.

ORDER BY PRO.PRO_IN_CODIGO
