/*--  SELECIONA OS PERIODOS PARA EXEC DE MANEIRA DINAMICA.

SELECT MAX(CUS.CPE_IN_CODIGO)-1 AS PRI_PER FROM MGCSC.CSC_MOVIMENTO CUS
SELECT MAX(CUS.CPE_IN_CODIGO)-3 AS PRI_PER FROM MGCSC.CSC_MOVIMENTO CUS

--==================================
--ITENS QUE POSSUEM LISTA DE MATERIAIS COM SUAS SERIES.

SELECT PRO.PRO_IN_CODIGO,
TO_NUMBER(SUBSTR(PRO.PRO_ST_CODREAL,3,4)) AS PRO_IN_SERIE  
FROM MGADM.EST_PRODUTOS PRO, mgadm.Est_Itenslistamateriais LIS
WHERE PRO.PRO_IN_CODIGO = LIS.PRO_IN_CODIGO
GROUP BY PRO.PRO_IN_CODIGO, PRO.PRO_ST_CODREAL 
ORDER BY PRO.PRO_IN_CODIGO

--=========================*/
--LISTA DE MATERIAIS MAIS RECENTE DE CADA ITEM
CREATE 
SELECT 
    ITENSLISTAMATERIAIS.PRO_IN_CODIGO  AS PA_PRO_IN_CODIGO,
    ITENSLISTAMATERIAIS.COM_IN_CODIGO  AS MP_PRO_IN_CODIGO
FROM  MGADM.EST_ITENSLISTAMATERIAIS   ITENSLISTAMATERIAIS
INNER JOIN
  (
  SELECT   ITENSLISTAMATERIAIS_AUX.PRO_IN_CODIGO,
      ITENSLISTAMATERIAIS_AUX.PRO_PAD_IN_CODIGO,
      ITENSLISTAMATERIAIS_AUX.PRO_TAB_IN_CODIGO,
      MAX(ITENSLISTAMATERIAIS_AUX.LIS_IN_REVISAO) AS REVMAX
  FROM  MGADM.EST_ITENSLISTAMATERIAIS   ITENSLISTAMATERIAIS_AUX
  GROUP BY ITENSLISTAMATERIAIS_AUX.PRO_IN_CODIGO,
       ITENSLISTAMATERIAIS_AUX.PRO_PAD_IN_CODIGO,
       ITENSLISTAMATERIAIS_AUX.PRO_TAB_IN_CODIGO
  ) TABAUX ON
ITENSLISTAMATERIAIS.PRO_IN_CODIGO     = TABAUX.PRO_IN_CODIGO     AND
ITENSLISTAMATERIAIS.PRO_PAD_IN_CODIGO = TABAUX.PRO_PAD_IN_CODIGO AND
ITENSLISTAMATERIAIS.PRO_TAB_IN_CODIGO = TABAUX.PRO_TAB_IN_CODIGO AND
ITENSLISTAMATERIAIS.LIS_IN_REVISAO    = TABAUX.REVMAX
AND ITENSLISTAMATERIAIS.PRO_IN_CODIGO =  4506    --TESTE

GROUP BY ITENSLISTAMATERIAIS.PRO_IN_CODIGO,
     ITENSLISTAMATERIAIS.PRO_TAB_IN_CODIGO,
     ITENSLISTAMATERIAIS.PRO_PAD_IN_CODIGO,
     ITENSLISTAMATERIAIS.LIS_IN_REVISAO,
     ITENSLISTAMATERIAIS.COM_IN_CODIGO,
     ITENSLISTAMATERIAIS.COM_TAB_IN_CODIGO,
     ITENSLISTAMATERIAIS.COM_PAD_IN_CODIGO


















