SELECT * FROM MGMAN.PRO_PLNOBSERVACAOPRO P, MGMAN.PRO_PROCESSOPRODUTO L
WHERE P.CPS_IN_CODIGO = L.CPS_IN_CODIGO
AND P.PRO_IN_CODIGO = L.PRO_IN_CODIGO
AND P.PRO_PAD_IN_CODIGO = L.PRO_PAD_IN_CODIGO
AND P.PRO_TAB_IN_CODIGO = L.PRO_TAB_IN_CODIGO
AND L.PLN_DT_REVISAO IN (select max(SU.pln_dt_revisao) from MGMAN.PRO_PROCESSOPRODUTO SU
                         where p.pro_in_codigo = SU.PRO_IN_CODIGO)

