select  RECEB.AGN_IN_CODIGO AGENTE,
        ITN.RCB_ST_NOTA NF, 
        ITN.RCB_DT_DOCUMENTO DATA_NF,
        upper(COMP.COMPL_ST_DESCRICAO) DESCRICAO, 
        ITN.PRO_IN_CODIGO COD_PROD, 
        ITN.RCI_RE_QUANTIDADE QTD, 
        ITN.UNI_ST_UNIDADE UNIDADE

FROM MGADM.EST_RECEBIMENTO RECEB, MGADM.EST_ITENSRECEB ITN, 
MGADM.EST_PRODUTOS PROD, MGADM.est_desccomplemento COMP

WHERE RECEB.RCB_ST_NOTA = ITN.RCB_ST_NOTA
AND   RECEB.RCB_DT_DOCUMENTO = ITN.RCB_DT_DOCUMENTO
AND   ITN.PRO_IN_CODIGO = PROD.PRO_IN_CODIGO

and    upper(comp.compl_st_descricao)  like ('%ZEBRA%')
--AND PROD.PRO_IN_CODIGO NOT IN (3286)

AND   RECEB.RCB_ST_NOTA = COMP.RCB_ST_NOTA
AND   RECEB.RCB_DT_DOCUMENTO = COMP.RCB_DT_DOCUMENTO
AND   COMP.COMPL_ST_TIPODOC = 'R'
AND   COMP.RCI_IN_SEQUENCIA = ITN.RCI_IN_SEQUENCIA
AND  RECEB.RCB_DT_DOCUMENTO > '01-JAN-2000'


AND RECEB.AGN_IN_CODIGO = 20752  -- APENAS NOTAS DA SINAL

ORDER BY RECEB.RCB_DT_DOCUMENTO desc

