CREATE OR REPLACE VIEW CLI_VW_HOME_DUPLICATA AS
Select 
REP.AGN_TAB_IN_CODIGO AS rep_in_codigo,
creb.MOV_DT_DATADOCTO as mov_dt_data,
creb.MOV_DT_PRORROGADO as mov_dt_prorrogado,
agn.agn_st_fantasia as agn_st_fantasia,
creb.MOV_ST_DOCUMENTO as mov_st_documento,
creb.MOV_ST_PARCELA as  mov_st_parcela,
creb.MOV_RE_VALOR as mov_re_valor,
creb.SALDO_EM_ABERTO as saldo_em_aberto,
((((NF.NOT_RE_VALORMERCADORIA-nf.Not_Re_Valordesconto-NF.Not_Re_Valorsuframa)*repnf.Rnf_Re_Perccomissao)/100)/cond.Cond_In_Parcelas) AS comissao

from MGVEN.VEN_NOTAFISCAL NF, MGGLO.GLO_AGENTES AGN, MGGLO.GLO_AGENTES REP, 
MGGLO.GLO_CONDPAGTO COND, MGFIN.FIN_VW_CONTASRECEBER CREB, 
MGVEN.VEN_REPRESENTANTENF REPNF, MGVEN.VEN_ITEMNOTAFISCAL ITNNF, MGVEN.VEN_REPRESENTANTEITEMNF REPITNNF

WHERE NF.NOT_IN_CODIGO   = ITNNF.NOT_IN_CODIGO
AND NF.SEQ_TAB_IN_CODIGO = ITNNF.SEQ_TAB_IN_CODIGO 
AND NF.SEQ_IN_CODIGO     = ITNNF.SEQ_IN_CODIGO     

AND ITNNF.NOT_IN_CODIGO     = REPITNNF.NOT_IN_CODIGO
AND ITNNF.SEQ_TAB_IN_CODIGO = REPITNNF.SEQ_TAB_IN_CODIGO
AND ITNNF.SEQ_IN_CODIGO     = REPITNNF.SEQ_IN_CODIGO         
AND ITNNF.ITN_IN_SEQUENCIA  = REPITNNF.ITN_IN_SEQUENCIA

AND NF.AGN_IN_CODIGO       = AGN.AGN_IN_CODIGO
AND NF.AGN_TAB_IN_CODIGO   = AGN.AGN_TAB_IN_CODIGO
AND NF.AGN_PAD_IN_CODIGO   = AGN.AGN_PAD_IN_CODIGO

AND NF.ACAO_TAB_IN_CODIGO  = CREB.ACAO_TAB_IN_CODIGO
AND NF.ACAO_PAD_IN_CODIGO  = CREB.ACAO_PAD_IN_CODIGO
AND NF.ACAO_IN_CODIGO      = CREB.ACAO_IN_CODIGO
AND NF.ACAOM_IN_SEQUENCIA  = CREB.ACAOM_IN_SEQUENCIA
AND CREB.TPD_ST_CODIGO    IN ('NFV','NFEV')
AND (CREB.SALDO_EM_ABERTO > 0.00 OR CREB.MOV_DT_VENCTO >= '01-JAN-2010')   

AND NF.COND_ST_CODIGO     = COND.COND_ST_CODIGO
AND NF.COND_PAD_IN_CODIGO = COND.COND_PAD_IN_CODIGO
AND NF.COND_TAB_IN_CODIGO = COND.COND_TAB_IN_CODIGO

AND NF.REP_TAB_IN_CODIGO  = REP.AGN_TAB_IN_CODIGO
AND NF.REP_PAD_IN_CODIGO  = REP.AGN_PAD_IN_CODIGO
AND NF.REP_IN_CODIGO      = REP.AGN_IN_CODIGO

AND NF.NOT_IN_CODIGO     = REPNF.NOT_IN_CODIGO
AND NF.SEQ_IN_CODIGO     = REPNF.SEQ_IN_CODIGO 
AND NF.SEQ_TAB_IN_CODIGO = REPNF.SEQ_TAB_IN_CODIGO 

--AND NF.NOT_DT_EMISSAO > '01-JAN-2018'

